spring.application.name=WayOfMilk
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=wayofmilk
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

grpc.server.port=9091
