spring.application.name=wom_t2


# T2 HTTP port (The port Blazor client will call)
server.port=8080

# gRPC Client Configuration for T3
# T2 will call the server named 'core-server' at localhost:9090
grpc.client.core-server.address=static://localhost:9090
grpc.client.core-server.enableKeepAlive=true
