package sep3.wayofmilk.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

import java.sql.Date;
import java.time.LocalDate;

@Entity public class Cow
{
  @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
  // DB handles ID generation
  //long instead of int because this is the standard for JPA entities
  private long id;
  private String regNo;
  private LocalDate birthDate; //LocalDate works better with JPA than Date
  //LocalDate accounts for time differences, so it's more accurate
  private boolean isHealthy= false; //upon adding a new cow to a herd,
  // it will be quarantined until health is confirmed, so the default is false

  //JPA requirement: Public or protected no-argument constructor
  //protected reserves this constructor for JPA only
  protected Cow()
  {
  }

  //constructor for adding a new cow to a herd, no id because it's generated by DB'
  public Cow(String regNo, LocalDate birthDate, boolean isHealthy)
  {
    this.regNo = regNo;
    this.birthDate = birthDate;
    this.isHealthy = isHealthy;
  }

  //getters and setters

  public long getId()
  {
    return id;
  }

  public void setId(long id)
  {
    this.id = id;
  }

  public String getRegNo()
  {
    return regNo;
  }

  public void setRegNo(String regNo)
  {
    this.regNo = regNo;
  }

  public LocalDate getBirthDate()
  {
    return birthDate;
  }

  public void setBirthDate(LocalDate birthDate)
  {
    this.birthDate = birthDate;
  }

  public boolean isHealthy()
  {
    return isHealthy;
  }

  public void setHealthy(boolean healthy)
  {
    isHealthy = healthy;
  }
}
